# Generated by Django 4.0.6 on 2022-07-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depozit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depozit',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
