# Generated by Django 4.0.6 on 2022-07-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depozit', '0002_depozit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depozit',
            name='price',
            field=models.PositiveIntegerField(verbose_name='summa (UZS)'),
        ),
    ]
