# Generated by Django 4.0.6 on 2022-07-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depozit', '0003_alter_depozit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depozit',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='summa (UZS)'),
        ),
    ]
