# Generated by Django 4.0.6 on 2022-07-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depozit', '0004_alter_depozit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='depozit',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
