# Generated by Django 4.0.6 on 2022-07-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('content', models.TextField(max_length=2048, null=True)),
                ('type', models.CharField(choices=[('salad', 'salatlar'), ('plov', 'osh')], max_length=16)),
            ],
        ),
    ]
