# Generated by Django 4.0.7 on 2022-08-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='id1',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='id1',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tgbot.basemodel'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tgbot.basemodel'),
        ),
    ]
