# Generated by Django 4.0.6 on 2022-07-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depozit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=64)),
                ('price', models.PositiveIntegerField(default=0, verbose_name='summa (UZS)')),
            ],
        ),
    ]
