# Generated by Django 4.0.6 on 2022-07-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xarajat', '0002_xarajat_delete_depozit'),
    ]

    operations = [
        migrations.AddField(
            model_name='xarajat',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
